-- ============================================================
-- DrivePro — QS Drive Pro-db
-- 01_schema.sql  (run FIRST in the Supabase SQL Editor)
-- Extensions, ENUM types, tables, constraints, indexes
-- ============================================================

-- ---------- EXTENSIONS ----------
create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ---------- ENUM TYPES ----------
create type user_role        as enum ('manager', 'secretary', 'instructor');
create type account_status   as enum ('active', 'inactive', 'suspended');
create type gender_type      as enum ('male', 'female');
create type student_status   as enum ('active', 'completed', 'suspended', 'withdrawn');
create type payment_method   as enum ('cash', 'momo', 'bank_transfer', 'cheque');
create type lesson_status    as enum ('scheduled', 'completed', 'cancelled', 'no_show');
create type vehicle_status   as enum ('available', 'in_use', 'maintenance', 'retired');
create type transmission_type as enum ('manual', 'automatic');
create type licence_stage    as enum (
  'not_started', 'learner_permit', 'theory_test',
  'practical_test', 'licence_issued'
);
create type expense_category as enum (
  'fuel', 'vehicle_maintenance', 'salaries', 'rent',
  'utilities', 'dvla_fees', 'stationery', 'other'
);

-- ---------- STAFF ----------
create table public.staff (
  id           uuid primary key default gen_random_uuid(),
  first_name   text not null,
  last_name    text not null,
  phone        text not null,
  email        text unique,
  role         user_role not null,
  hire_date    date not null default current_date,
  status       account_status not null default 'active',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------- USERS (linked 1:1 to Supabase Auth) ----------
create table public.users (
  id           uuid primary key references auth.users (id) on delete cascade,
  email        text not null unique,
  role         user_role not null,
  staff_id     uuid unique references public.staff (id) on delete set null,
  status       account_status not null default 'active',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------- STUDENTS ----------
create table public.students (
  id                uuid primary key default gen_random_uuid(),
  student_number    text unique,           -- auto-generated by trigger (02)
  first_name        text not null,
  last_name         text not null,
  gender            gender_type not null,
  dob               date not null,
  phone             text not null,
  email             text,
  address           text,
  emergency_contact text,
  ghana_card_no     text unique,
  photo_url         text,
  registration_date date not null default current_date,
  status            student_status not null default 'active',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint chk_students_dob check (dob < current_date)
);

-- ---------- DRIVING PACKAGES ----------
create table public.driving_packages (
  id             uuid primary key default gen_random_uuid(),
  package_name   text not null unique,
  duration_weeks int  not null check (duration_weeks > 0),
  lesson_count   int  not null check (lesson_count > 0),
  total_fee      numeric(10,2) not null check (total_fee >= 0),
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ---------- STUDENT PACKAGES (enrolment) ----------
create table public.student_packages (
  id            uuid primary key default gen_random_uuid(),
  student_id    uuid not null references public.students (id) on delete cascade,
  package_id    uuid not null references public.driving_packages (id),
  assigned_date date not null default current_date,
  created_at    timestamptz not null default now(),
  unique (student_id, package_id, assigned_date)
);

-- ---------- VEHICLES ----------
create table public.vehicles (
  id           uuid primary key default gen_random_uuid(),
  reg_no       text not null unique,
  make         text not null,
  model        text not null,
  transmission transmission_type not null,
  status       vehicle_status not null default 'available',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------- PAYMENTS ----------
create table public.payments (
  id           uuid primary key default gen_random_uuid(),
  student_id   uuid not null references public.students (id) on delete restrict,
  amount       numeric(10,2) not null check (amount > 0),
  method       payment_method not null,
  payment_date date not null default current_date,
  recorded_by  uuid references public.users (id),
  notes        text,
  created_at   timestamptz not null default now()
);

-- ---------- RECEIPTS (1:1 with payments, auto-created by trigger) ----------
create table public.receipts (
  id         uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.payments (id) on delete cascade,
  receipt_no text not null unique,
  issued_at  timestamptz not null default now(),
  pdf_url    text
);

-- ---------- LESSON SCHEDULE ----------
create table public.lesson_schedule (
  id            uuid primary key default gen_random_uuid(),
  student_id    uuid not null references public.students (id) on delete cascade,
  instructor_id uuid not null references public.staff (id),
  vehicle_id    uuid references public.vehicles (id),
  lesson_date   date not null,
  start_time    time not null,
  end_time      time not null,
  status        lesson_status not null default 'scheduled',
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint chk_lesson_times check (end_time > start_time)
);

-- ---------- LESSON PROGRESS ----------
create table public.lesson_progress (
  id              uuid primary key default gen_random_uuid(),
  student_id      uuid not null references public.students (id) on delete cascade,
  instructor_id   uuid not null references public.staff (id),
  lesson_number   int  not null check (lesson_number > 0),
  topic           text not null,
  performance     text,                          -- e.g. excellent / good / needs work
  completed       boolean not null default false,
  completion_date date,
  remarks         text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (student_id, lesson_number)
);

-- ---------- LICENCE TRACKING ----------
create table public.licence_tracking (
  id         uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students (id) on delete cascade,
  stage      licence_stage not null default 'not_started',
  updated_by uuid references public.users (id),
  updated_at timestamptz not null default now(),
  remarks    text
);

-- ---------- EXPENSES ----------
create table public.expenses (
  id           uuid primary key default gen_random_uuid(),
  category     expense_category not null,
  amount       numeric(10,2) not null check (amount > 0),
  description  text,
  expense_date date not null default current_date,
  created_by   uuid references public.users (id),
  created_at   timestamptz not null default now()
);

-- ---------- AUDIT LOGS ----------
create table public.audit_logs (
  id         bigint generated always as identity primary key,
  user_id    uuid,
  table_name text not null,
  record_id  text,
  action     text not null,            -- INSERT / UPDATE / DELETE
  old_data   jsonb,
  new_data   jsonb,
  created_at timestamptz not null default now()
);

-- ---------- INDEXES ----------
create index idx_students_name        on public.students (last_name, first_name);
create index idx_students_status      on public.students (status);
create index idx_payments_student     on public.payments (student_id);
create index idx_payments_date        on public.payments (payment_date);
create index idx_schedule_student     on public.lesson_schedule (student_id);
create index idx_schedule_instructor  on public.lesson_schedule (instructor_id);
create index idx_schedule_date        on public.lesson_schedule (lesson_date);
create index idx_progress_student     on public.lesson_progress (student_id);
create index idx_progress_instructor  on public.lesson_progress (instructor_id);
create index idx_licence_student      on public.licence_tracking (student_id);
create index idx_expenses_date        on public.expenses (expense_date);
create index idx_audit_table          on public.audit_logs (table_name, created_at);
create index idx_student_pkg_student  on public.student_packages (student_id);
