-- ============================================================
-- QS Drive Pro-db — COMPLETE BACKEND, single run
-- Paste this entire file into: Supabase Dashboard → SQL Editor
-- Click RUN once. Expected result: "Success. No rows returned."
-- (Combines migrations 01–06 in the correct order)
-- ============================================================

-- ============================================================
-- DrivePro — QS Drive Pro-db
-- 01_schema.sql  (run FIRST in the Supabase SQL Editor)
-- Extensions, ENUM types, tables, constraints, indexes
-- ============================================================

-- ---------- EXTENSIONS ----------
create extension if not exists pgcrypto;   -- gen_random_uuid()

-- ---------- ENUM TYPES ----------
create type user_role        as enum ('manager', 'secretary', 'instructor');
create type account_status   as enum ('active', 'inactive', 'suspended');
create type gender_type      as enum ('male', 'female');
create type student_status   as enum ('active', 'completed', 'suspended', 'withdrawn');
create type payment_method   as enum ('cash', 'momo', 'bank_transfer', 'cheque');
create type lesson_status    as enum ('scheduled', 'completed', 'cancelled', 'no_show');
create type vehicle_status   as enum ('available', 'in_use', 'maintenance', 'retired');
create type transmission_type as enum ('manual', 'automatic');
create type licence_stage    as enum (
  'not_started', 'learner_permit', 'theory_test',
  'practical_test', 'licence_issued'
);
create type expense_category as enum (
  'fuel', 'vehicle_maintenance', 'salaries', 'rent',
  'utilities', 'dvla_fees', 'stationery', 'other'
);

-- ---------- STAFF ----------
create table public.staff (
  id           uuid primary key default gen_random_uuid(),
  first_name   text not null,
  last_name    text not null,
  phone        text not null,
  email        text unique,
  role         user_role not null,
  hire_date    date not null default current_date,
  status       account_status not null default 'active',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------- USERS (linked 1:1 to Supabase Auth) ----------
create table public.users (
  id           uuid primary key references auth.users (id) on delete cascade,
  email        text not null unique,
  role         user_role not null,
  staff_id     uuid unique references public.staff (id) on delete set null,
  status       account_status not null default 'active',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------- STUDENTS ----------
create table public.students (
  id                uuid primary key default gen_random_uuid(),
  student_number    text unique,           -- auto-generated by trigger (02)
  first_name        text not null,
  last_name         text not null,
  gender            gender_type not null,
  dob               date not null,
  phone             text not null,
  email             text,
  address           text,
  emergency_contact text,
  ghana_card_no     text unique,
  id_card_type      text check (id_card_type in ('Ghana Card', 'Voter ID', 'Passport', 'Driver''s Licence', 'Other')),
  photo_url         text,
  registration_date date not null default current_date,
  status            student_status not null default 'active',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint chk_students_dob check (dob < current_date)
);

-- ---------- DRIVING PACKAGES ----------
create table public.driving_packages (
  id             uuid primary key default gen_random_uuid(),
  package_name   text not null unique,
  duration_weeks int  not null check (duration_weeks > 0),
  lesson_count   int  not null check (lesson_count > 0),
  total_fee      numeric(10,2) not null check (total_fee >= 0),
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ---------- STUDENT PACKAGES (enrolment) ----------
create table public.student_packages (
  id            uuid primary key default gen_random_uuid(),
  student_id    uuid not null references public.students (id) on delete cascade,
  package_id    uuid not null references public.driving_packages (id),
  assigned_date date not null default current_date,
  created_at    timestamptz not null default now(),
  unique (student_id, package_id, assigned_date)
);

-- ---------- VEHICLES ----------
create table public.vehicles (
  id           uuid primary key default gen_random_uuid(),
  reg_no       text not null unique,
  make         text not null,
  model        text not null,
  transmission transmission_type not null,
  status       vehicle_status not null default 'available',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------- PAYMENTS ----------
create table public.payments (
  id           uuid primary key default gen_random_uuid(),
  student_id   uuid not null references public.students (id) on delete restrict,
  amount       numeric(10,2) not null check (amount > 0),
  method       payment_method not null,
  payment_date date not null default current_date,
  recorded_by  uuid references public.users (id),
  notes        text,
  created_at   timestamptz not null default now()
);

-- ---------- RECEIPTS (1:1 with payments, auto-created by trigger) ----------
create table public.receipts (
  id         uuid primary key default gen_random_uuid(),
  payment_id uuid not null unique references public.payments (id) on delete cascade,
  receipt_no text not null unique,
  issued_at  timestamptz not null default now(),
  pdf_url    text
);

-- ---------- LESSON SCHEDULE ----------
create table public.lesson_schedule (
  id            uuid primary key default gen_random_uuid(),
  student_id    uuid not null references public.students (id) on delete cascade,
  instructor_id uuid not null references public.staff (id),
  vehicle_id    uuid references public.vehicles (id),
  lesson_date   date not null,
  start_time    time not null,
  end_time      time not null,
  status        lesson_status not null default 'scheduled',
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint chk_lesson_times check (end_time > start_time)
);

-- ---------- LESSON PROGRESS ----------
create table public.lesson_progress (
  id              uuid primary key default gen_random_uuid(),
  student_id      uuid not null references public.students (id) on delete cascade,
  instructor_id   uuid not null references public.staff (id),
  lesson_number   int  not null check (lesson_number > 0),
  topic           text not null,
  performance     text,                          -- e.g. excellent / good / needs work
  completed       boolean not null default false,
  completion_date date,
  remarks         text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  unique (student_id, lesson_number)
);

-- ---------- LICENCE TRACKING ----------
create table public.licence_tracking (
  id         uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students (id) on delete cascade,
  stage      licence_stage not null default 'not_started',
  updated_by uuid references public.users (id),
  updated_at timestamptz not null default now(),
  remarks    text
);

-- ---------- EXPENSES ----------
create table public.expenses (
  id           uuid primary key default gen_random_uuid(),
  category     expense_category not null,
  amount       numeric(10,2) not null check (amount > 0),
  description  text,
  expense_date date not null default current_date,
  created_by   uuid references public.users (id),
  created_at   timestamptz not null default now()
);

-- ---------- AUDIT LOGS ----------
create table public.audit_logs (
  id         bigint generated always as identity primary key,
  user_id    uuid,
  table_name text not null,
  record_id  text,
  action     text not null,            -- INSERT / UPDATE / DELETE
  old_data   jsonb,
  new_data   jsonb,
  created_at timestamptz not null default now()
);

-- ---------- INDEXES ----------
create index idx_students_name        on public.students (last_name, first_name);
create index idx_students_status      on public.students (status);
create index idx_payments_student     on public.payments (student_id);
create index idx_payments_date        on public.payments (payment_date);
create index idx_schedule_student     on public.lesson_schedule (student_id);
create index idx_schedule_instructor  on public.lesson_schedule (instructor_id);
create index idx_schedule_date        on public.lesson_schedule (lesson_date);
create index idx_progress_student     on public.lesson_progress (student_id);
create index idx_progress_instructor  on public.lesson_progress (instructor_id);
create index idx_licence_student      on public.licence_tracking (student_id);
create index idx_expenses_date        on public.expenses (expense_date);
create index idx_audit_table          on public.audit_logs (table_name, created_at);
create index idx_student_pkg_student  on public.student_packages (student_id);
-- ============================================================
-- DrivePro — 02_functions_triggers.sql  (run SECOND)
-- Auto-numbering, updated_at maintenance, audit logging, views
-- ============================================================

-- ---------- SEQUENCES ----------
create sequence if not exists student_number_seq start 1;
create sequence if not exists receipt_number_seq start 1;

-- ---------- AUTO STUDENT NUMBER: DP-2026-0001 ----------
create or replace function public.set_student_number()
returns trigger
language plpgsql
as $$
begin
  if new.student_number is null then
    new.student_number :=
      'DP-' || to_char(now(), 'YYYY') || '-' ||
      lpad(nextval('student_number_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

create trigger trg_student_number
before insert on public.students
for each row execute function public.set_student_number();

-- ---------- AUTO RECEIPT ON EVERY PAYMENT: RCT-000001 ----------
create or replace function public.create_receipt_for_payment()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.receipts (payment_id, receipt_no)
  values (
    new.id,
    'RCT-' || lpad(nextval('receipt_number_seq')::text, 6, '0')
  );
  return new;
end;
$$;

create trigger trg_auto_receipt
after insert on public.payments
for each row execute function public.create_receipt_for_payment();

-- ---------- UPDATED_AT MAINTENANCE ----------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_touch_staff       before update on public.staff            for each row execute function public.touch_updated_at();
create trigger trg_touch_users       before update on public.users            for each row execute function public.touch_updated_at();
create trigger trg_touch_students    before update on public.students         for each row execute function public.touch_updated_at();
create trigger trg_touch_packages    before update on public.driving_packages for each row execute function public.touch_updated_at();
create trigger trg_touch_vehicles    before update on public.vehicles         for each row execute function public.touch_updated_at();
create trigger trg_touch_schedule    before update on public.lesson_schedule  for each row execute function public.touch_updated_at();
create trigger trg_touch_progress    before update on public.lesson_progress  for each row execute function public.touch_updated_at();

-- ---------- GENERIC AUDIT LOGGING ----------
-- Records who changed what, with before/after snapshots.
create or replace function public.audit_changes()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.audit_logs (user_id, table_name, record_id, action, old_data, new_data)
  values (
    auth.uid(),
    tg_table_name,
    coalesce((to_jsonb(new) ->> 'id'), (to_jsonb(old) ->> 'id')),
    tg_op,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;

-- Attach auditing to the sensitive tables
create trigger trg_audit_students  after insert or update or delete on public.students         for each row execute function public.audit_changes();
create trigger trg_audit_payments  after insert or update or delete on public.payments         for each row execute function public.audit_changes();
create trigger trg_audit_staff     after insert or update or delete on public.staff            for each row execute function public.audit_changes();
create trigger trg_audit_licence   after insert or update or delete on public.licence_tracking for each row execute function public.audit_changes();
create trigger trg_audit_expenses  after insert or update or delete on public.expenses         for each row execute function public.audit_changes();
create trigger trg_audit_packages  after insert or update or delete on public.student_packages for each row execute function public.audit_changes();

-- ---------- REPORTING VIEWS ----------

-- Total fees vs total paid vs balance, per student
create or replace view public.v_student_balances as
select
  s.id,
  s.student_number,
  s.first_name || ' ' || s.last_name        as student_name,
  s.status,
  coalesce(fees.total_fees, 0)              as total_fees,
  coalesce(paid.total_paid, 0)              as total_paid,
  coalesce(fees.total_fees, 0)
    - coalesce(paid.total_paid, 0)          as balance
from public.students s
left join (
  select sp.student_id, sum(dp.total_fee) as total_fees
  from public.student_packages sp
  join public.driving_packages dp on dp.id = sp.package_id
  group by sp.student_id
) fees on fees.student_id = s.id
left join (
  select p.student_id, sum(p.amount) as total_paid
  from public.payments p
  group by p.student_id
) paid on paid.student_id = s.id;

-- Monthly revenue
create or replace view public.v_monthly_revenue as
select
  to_char(payment_date, 'YYYY-MM') as month,
  count(*)                         as payment_count,
  sum(amount)                      as total_revenue
from public.payments
group by 1
order by 1 desc;

-- Upcoming lessons with names joined in
create or replace view public.v_upcoming_lessons as
select
  ls.id,
  ls.lesson_date,
  ls.start_time,
  ls.end_time,
  ls.status,
  st.student_number,
  st.first_name || ' ' || st.last_name as student_name,
  sf.first_name || ' ' || sf.last_name as instructor_name,
  v.reg_no                             as vehicle
from public.lesson_schedule ls
join public.students st on st.id = ls.student_id
join public.staff    sf on sf.id = ls.instructor_id
left join public.vehicles v on v.id = ls.vehicle_id
where ls.lesson_date >= current_date
  and ls.status = 'scheduled'
order by ls.lesson_date, ls.start_time;

-- Manager dashboard stats in one call:  select * from v_dashboard_stats;
create or replace view public.v_dashboard_stats as
select
  (select count(*) from public.students)                                        as total_students,
  (select count(*) from public.students where status = 'active')                as active_students,
  (select coalesce(sum(amount),0) from public.payments
     where date_trunc('month', payment_date) = date_trunc('month', now()))     as revenue_this_month,
  (select coalesce(sum(balance),0) from public.v_student_balances
     where balance > 0)                                                        as outstanding_balances,
  (select count(*) from public.lesson_progress where completed)                as lessons_completed,
  (select count(*) from public.licence_tracking where stage='licence_issued')  as licences_issued,
  (select count(*) from public.lesson_schedule
     where lesson_date >= current_date and status='scheduled')                 as upcoming_lessons,
  (select coalesce(sum(amount),0) from public.expenses
     where date_trunc('month', expense_date) = date_trunc('month', now()))     as expenses_this_month;
-- ============================================================
-- DrivePro — 03_rls_policies.sql  (run THIRD)
-- Row-Level Security: Manager / Secretary / Instructor
-- ============================================================

-- ---------- HELPER FUNCTIONS ----------
-- Role of the currently logged-in user
create or replace function public.get_my_role()
returns user_role
language sql
stable
security definer
as $$
  select role from public.users where id = auth.uid();
$$;

-- staff.id of the currently logged-in user (for instructors)
create or replace function public.get_my_staff_id()
returns uuid
language sql
stable
security definer
as $$
  select staff_id from public.users where id = auth.uid();
$$;

-- ---------- ENABLE RLS ON ALL TABLES ----------
alter table public.users            enable row level security;
alter table public.staff            enable row level security;
alter table public.students         enable row level security;
alter table public.driving_packages enable row level security;
alter table public.student_packages enable row level security;
alter table public.payments         enable row level security;
alter table public.receipts         enable row level security;
alter table public.vehicles         enable row level security;
alter table public.lesson_schedule  enable row level security;
alter table public.lesson_progress  enable row level security;
alter table public.licence_tracking enable row level security;
alter table public.expenses         enable row level security;
alter table public.audit_logs       enable row level security;

-- ============================================================
-- USERS — everyone can read their own profile; managers manage all
-- ============================================================
create policy users_select_own on public.users
  for select using (id = auth.uid() or public.get_my_role() = 'manager');

create policy users_manager_all on public.users
  for all using (public.get_my_role() = 'manager')
  with check (public.get_my_role() = 'manager');

-- ============================================================
-- MANAGER — full access to everything
-- ============================================================
create policy mgr_staff    on public.staff            for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_students on public.students         for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_pkgs     on public.driving_packages for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_spkgs    on public.student_packages for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_pay      on public.payments         for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_rcpt     on public.receipts         for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_veh      on public.vehicles         for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_sched    on public.lesson_schedule  for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_prog     on public.lesson_progress  for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_lic      on public.licence_tracking for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_exp      on public.expenses         for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');

-- Audit logs: manager can READ ONLY (nobody can edit or delete them)
create policy mgr_audit_read on public.audit_logs
  for select using (public.get_my_role() = 'manager');

-- ============================================================
-- SECRETARY — manage students, enrolments, payments, scheduling.
-- No access to audit logs, expenses, or staff management.
-- ============================================================
create policy sec_students on public.students
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');

create policy sec_spkgs on public.student_packages
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');

create policy sec_pay on public.payments
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');

create policy sec_rcpt_read on public.receipts
  for select using (public.get_my_role()='secretary');

create policy sec_sched on public.lesson_schedule
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');

create policy sec_lic on public.licence_tracking
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');

create policy sec_pkgs_read on public.driving_packages
  for select using (public.get_my_role()='secretary');

create policy sec_veh_read on public.vehicles
  for select using (public.get_my_role()='secretary');

create policy sec_staff_read on public.staff
  for select using (public.get_my_role()='secretary');

create policy sec_prog_read on public.lesson_progress
  for select using (public.get_my_role()='secretary');

-- ============================================================
-- INSTRUCTOR — read own schedule + assigned students;
-- update lesson progress for own lessons only.
-- ============================================================
create policy ins_sched_read on public.lesson_schedule
  for select using (
    public.get_my_role()='instructor'
    and instructor_id = public.get_my_staff_id()
  );

create policy ins_students_read on public.students
  for select using (
    public.get_my_role()='instructor'
    and id in (
      select student_id from public.lesson_schedule
      where instructor_id = public.get_my_staff_id()
    )
  );

create policy ins_prog_select on public.lesson_progress
  for select using (
    public.get_my_role()='instructor'
    and instructor_id = public.get_my_staff_id()
  );

create policy ins_prog_insert on public.lesson_progress
  for insert with check (
    public.get_my_role()='instructor'
    and instructor_id = public.get_my_staff_id()
  );

create policy ins_prog_update on public.lesson_progress
  for update using (
    public.get_my_role()='instructor'
    and instructor_id = public.get_my_staff_id()
  ) with check (
    instructor_id = public.get_my_staff_id()
  );

create policy ins_veh_read on public.vehicles
  for select using (public.get_my_role()='instructor');

create policy ins_staff_read_self on public.staff
  for select using (
    public.get_my_role()='instructor'
    and id = public.get_my_staff_id()
  );
-- ============================================================
-- DrivePro — 04_storage_seed.sql  (run FOURTH)
-- Storage buckets + sample data for testing
-- ============================================================

-- ---------- STORAGE BUCKETS (all private) ----------
insert into storage.buckets (id, name, public)
values
  ('student-photos',    'student-photos',    false),
  ('ghana-cards',       'ghana-cards',       false),
  ('licence-documents', 'licence-documents', false),
  ('receipts',          'receipts',          false)
on conflict (id) do nothing;

-- Storage access: manager + secretary can manage files; instructor can view photos
create policy storage_staff_all on storage.objects
  for all using (
    bucket_id in ('student-photos','ghana-cards','licence-documents','receipts')
    and public.get_my_role() in ('manager','secretary')
  ) with check (
    bucket_id in ('student-photos','ghana-cards','licence-documents','receipts')
    and public.get_my_role() in ('manager','secretary')
  );

create policy storage_instructor_photos on storage.objects
  for select using (
    bucket_id = 'student-photos'
    and public.get_my_role() = 'instructor'
  );

-- ---------- SAMPLE DRIVING PACKAGES ----------
insert into public.driving_packages (package_name, duration_weeks, lesson_count, total_fee)
values
  ('Beginner Package',      6,  12, 1500.00),
  ('Standard Package',      8,  16, 2000.00),
  ('Intensive Package',     4,  12, 1800.00),
  ('Refresher Course',      2,   4,  600.00),
  ('Automatic Only',        6,  10, 1400.00);

-- ---------- SAMPLE VEHICLES ----------
insert into public.vehicles (reg_no, make, model, transmission, status)
values
  ('GR-1234-24', 'Toyota',  'Corolla', 'manual',    'available'),
  ('GR-5678-24', 'Hyundai', 'Accent',  'automatic', 'available'),
  ('GW-9012-23', 'Kia',     'Rio',     'manual',    'maintenance');

-- ---------- SAMPLE STAFF ----------
insert into public.staff (first_name, last_name, phone, email, role, hire_date)
values
  ('Kwame',  'Mensah',  '0244000001', 'manager@drivepro.test',    'manager',    '2023-01-10'),
  ('Akosua', 'Boateng', '0244000002', 'secretary@drivepro.test',  'secretary',  '2023-03-15'),
  ('Yaw',    'Owusu',   '0244000003', 'instructor1@drivepro.test','instructor', '2023-02-01'),
  ('Ama',    'Asante',  '0244000004', 'instructor2@drivepro.test','instructor', '2024-06-20');

-- NOTE: sample students/payments are best created through the app UI
-- so that triggers (student numbers, receipts, audit logs) fire with a
-- real logged-in user. But you can insert a quick test student:
insert into public.students (first_name, last_name, gender, dob, phone, email)
values ('Kofi', 'Adjei', 'male', '2000-05-14', '0550000001', 'kofi.test@example.com');
-- ============================================================
-- DrivePro / Quick Start Pro — 05_ui_alignment.sql  (run FIFTH)
-- Aligns the backend with the App Screens UI design:
--   attendance + QR check-in, recurring weekly slots,
--   daily records & end-of-day approval, notifications,
--   settings, role permission matrix, R-#### receipts
-- ============================================================

-- ---------- NEW ENUM TYPES ----------
create type attendance_status  as enum ('present', 'absent', 'late', 'excused');
create type checkin_method     as enum ('self_qr', 'manual');
create type day_status         as enum ('open', 'pending_approval', 'closed');
create type notification_type  as enum (
  'payment_due', 'lesson_reminder', 'missed_lesson',
  'audit_alert', 'end_of_day', 'security', 'system'
);

-- ============================================================
-- 1. RECURRING WEEKLY SCHEDULE (Mon–Sat slot grid)
-- ============================================================
create table public.schedule_slots (
  id          uuid primary key default gen_random_uuid(),
  day_of_week int  not null check (day_of_week between 1 and 6),  -- 1=Mon … 6=Sat
  start_time  time not null,
  end_time    time not null,
  capacity    int  not null default 4 check (capacity > 0),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now(),
  unique (day_of_week, start_time),
  constraint chk_slot_times check (end_time > start_time)
);

create table public.slot_assignments (
  id            uuid primary key default gen_random_uuid(),
  slot_id       uuid not null references public.schedule_slots (id) on delete cascade,
  student_id    uuid not null references public.students (id) on delete cascade,
  assigned_date date not null default current_date,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  unique (slot_id, student_id)
);

create index idx_slot_assign_student on public.slot_assignments (student_id);
create index idx_slot_assign_slot    on public.slot_assignments (slot_id);

-- Pre-create the standard grid: Mon–Sat, 8am–5pm hourly slots
insert into public.schedule_slots (day_of_week, start_time, end_time)
select d, make_time(h, 0, 0), make_time(h + 1, 0, 0)
from generate_series(1, 6) d, generate_series(8, 16) h;

-- ============================================================
-- 2. ATTENDANCE (QR self check-in, manual marking, walk-ins)
-- ============================================================
create table public.attendance (
  id              uuid primary key default gen_random_uuid(),
  student_id      uuid not null references public.students (id) on delete cascade,
  attendance_date date not null default current_date,
  slot_id         uuid references public.schedule_slots (id),   -- NULL = walk-in / no slot
  check_in_time   timestamptz,
  method          checkin_method not null default 'manual',
  status          attendance_status not null default 'present',
  is_walk_in      boolean not null default false,
  marked_by       uuid references public.users (id),            -- NULL if self check-in
  notes           text,
  created_at      timestamptz not null default now(),
  unique (student_id, attendance_date)
);

create index idx_attendance_date    on public.attendance (attendance_date);
create index idx_attendance_student on public.attendance (student_id);

-- Attendance counts toward "lessons left"
create or replace view public.v_lessons_remaining as
select
  s.id                                   as student_id,
  s.student_number,
  s.first_name || ' ' || s.last_name     as student_name,
  coalesce(pkg.total_lessons, 0)         as total_lessons,
  coalesce(att.attended, 0)              as lessons_used,
  coalesce(pkg.total_lessons, 0)
    - coalesce(att.attended, 0)          as lessons_left
from public.students s
left join (
  select sp.student_id, sum(dp.lesson_count) as total_lessons
  from public.student_packages sp
  join public.driving_packages dp on dp.id = sp.package_id
  group by sp.student_id
) pkg on pkg.student_id = s.id
left join (
  select student_id, count(*) as attended
  from public.attendance
  where status in ('present', 'late')
  group by student_id
) att on att.student_id = s.id;

-- Today's attendance screen in one query
create or replace view public.v_today_attendance as
select
  st.id                                as student_id,
  st.first_name || ' ' || st.last_name as student_name,
  sl.start_time,
  sl.end_time,
  a.check_in_time,
  a.method,
  a.status,
  a.is_walk_in,
  lr.lessons_left
from public.students st
left join public.slot_assignments sa
  on sa.student_id = st.id and sa.is_active
left join public.schedule_slots sl
  on sl.id = sa.slot_id
 and sl.day_of_week = extract(isodow from current_date)
left join public.attendance a
  on a.student_id = st.id and a.attendance_date = current_date
left join public.v_lessons_remaining lr
  on lr.student_id = st.id
where sl.id is not null or a.id is not null;

-- ============================================================
-- 3. DAILY RECORDS + END-OF-DAY WORKFLOW
--    Secretary submits → Manager approves & closes
-- ============================================================
create table public.daily_closures (
  id              uuid primary key default gen_random_uuid(),
  closure_date    date not null unique,
  opening_balance numeric(12,2) not null default 0,
  total_income    numeric(12,2) not null default 0,
  total_expenses  numeric(12,2) not null default 0,
  closing_balance numeric(12,2) not null default 0,
  status          day_status not null default 'open',
  submitted_by    uuid references public.users (id),
  submitted_at    timestamptz,
  approved_by     uuid references public.users (id),
  approved_at     timestamptz,
  remarks         text,
  created_at      timestamptz not null default now()
);

-- Unified day ledger (income + expenses interleaved) → powers the Records screen
create or replace view public.v_daily_ledger as
select
  p.payment_date                        as entry_date,
  p.created_at                          as entry_time,
  st.first_name || ' ' || st.last_name || ' (payment)' as description,
  'Income'                              as category,
  p.amount                              as income,
  null::numeric                         as expense
from public.payments p
join public.students st on st.id = p.student_id
union all
select
  e.expense_date,
  e.created_at,
  coalesce(e.description, e.category::text),
  initcap(replace(e.category::text, '_', ' ')),
  null::numeric,
  e.amount
from public.expenses e
order by entry_date, entry_time;

-- Secretary calls this to submit the day (computes totals automatically):
--   select public.submit_end_of_day(current_date);
create or replace function public.submit_end_of_day(p_date date)
returns public.daily_closures
language plpgsql
security definer
as $$
declare
  v_open   numeric(12,2);
  v_income numeric(12,2);
  v_exp    numeric(12,2);
  v_row    public.daily_closures;
begin
  select coalesce(
    (select closing_balance from public.daily_closures
      where closure_date < p_date and status = 'closed'
      order by closure_date desc limit 1), 0)
  into v_open;

  select coalesce(sum(amount), 0) into v_income
  from public.payments where payment_date = p_date;

  select coalesce(sum(amount), 0) into v_exp
  from public.expenses where expense_date = p_date;

  insert into public.daily_closures
    (closure_date, opening_balance, total_income, total_expenses,
     closing_balance, status, submitted_by, submitted_at)
  values
    (p_date, v_open, v_income, v_exp,
     v_open + v_income - v_exp, 'pending_approval', auth.uid(), now())
  on conflict (closure_date) do update
    set opening_balance = excluded.opening_balance,
        total_income    = excluded.total_income,
        total_expenses  = excluded.total_expenses,
        closing_balance = excluded.closing_balance,
        status          = 'pending_approval',
        submitted_by    = auth.uid(),
        submitted_at    = now()
  returning * into v_row;

  -- Notify the manager
  insert into public.notifications (recipient_role, type, title, body, link_url)
  values ('manager', 'end_of_day',
          'End of day submitted — review needed',
          to_char(p_date, 'FMDay DD Mon') || ' submitted for approval',
          '/finances');
  return v_row;
end;
$$;

-- Manager calls this to approve & close:
--   select public.approve_end_of_day(current_date);
create or replace function public.approve_end_of_day(p_date date)
returns public.daily_closures
language plpgsql
security definer
as $$
declare
  v_row public.daily_closures;
begin
  if public.get_my_role() <> 'manager' then
    raise exception 'Only the manager can approve and close a day';
  end if;

  update public.daily_closures
     set status = 'closed', approved_by = auth.uid(), approved_at = now()
   where closure_date = p_date and status = 'pending_approval'
  returning * into v_row;

  if v_row.id is null then
    raise exception 'No pending submission found for %', p_date;
  end if;
  return v_row;
end;
$$;

-- Once a day is CLOSED, its payments and expenses are locked
create or replace function public.block_closed_day_changes()
returns trigger
language plpgsql
as $$
declare
  v_date date;
begin
  v_date := coalesce(
    (to_jsonb(new) ->> 'payment_date')::date,
    (to_jsonb(new) ->> 'expense_date')::date,
    (to_jsonb(old) ->> 'payment_date')::date,
    (to_jsonb(old) ->> 'expense_date')::date
  );
  if exists (select 1 from public.daily_closures
             where closure_date = v_date and status = 'closed') then
    raise exception 'Day % is closed and approved — records can no longer be changed', v_date;
  end if;
  return coalesce(new, old);
end;
$$;

create trigger trg_lock_payments before insert or update or delete on public.payments
  for each row execute function public.block_closed_day_changes();
create trigger trg_lock_expenses before insert or update or delete on public.expenses
  for each row execute function public.block_closed_day_changes();

-- ============================================================
-- 4. NOTIFICATIONS
-- ============================================================
create table public.notifications (
  id             uuid primary key default gen_random_uuid(),
  recipient_role user_role,                                -- broadcast to a role…
  recipient_user uuid references public.users (id),        -- …or a specific user
  type           notification_type not null,
  title          text not null,
  body           text,
  link_url       text,
  is_read        boolean not null default false,
  created_at     timestamptz not null default now(),
  constraint chk_recipient check (recipient_role is not null or recipient_user is not null)
);

create index idx_notif_role on public.notifications (recipient_role, is_read);
create index idx_notif_user on public.notifications (recipient_user, is_read);

-- Alert the manager whenever a payment amount is EDITED (matches
-- the "Vital record edited" notification in the design)
create or replace function public.notify_payment_edit()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.amount is distinct from old.amount then
    insert into public.notifications (recipient_role, type, title, body, link_url)
    values ('manager', 'audit_alert',
            'Vital record edited — payment amount changed',
            'Amount changed from GHS ' || old.amount || ' to GHS ' || new.amount,
            '/audit-log');
  end if;
  return new;
end;
$$;

create trigger trg_notify_payment_edit
after update on public.payments
for each row execute function public.notify_payment_edit();

-- ============================================================
-- 5. SETTINGS + ROLE PERMISSION MATRIX
-- ============================================================
create table public.app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_by uuid references public.users (id),
  updated_at timestamptz not null default now()
);

insert into public.app_settings (key, value) values
  ('school_name',    '"Quick Start Driving School"'),
  ('app_name',       '"Quick Start Pro"'),
  ('business_phone', '"030 222 4455"'),
  ('address',        '"Spintex Road, Accra"'),
  ('currency',       '"GHS"');

create table public.role_permissions (
  id               uuid primary key default gen_random_uuid(),
  role             user_role not null,
  permission_key   text not null,
  allowed          boolean not null default true,
  requires_logging boolean not null default false,
  unique (role, permission_key)
);

insert into public.role_permissions (role, permission_key, allowed, requires_logging) values
  ('manager',   'students.view',              true,  false),
  ('secretary', 'students.view',              true,  false),
  ('manager',   'students.delete',            true,  false),
  ('secretary', 'students.delete',            false, false),
  ('manager',   'students.override_duplicate',true,  false),
  ('secretary', 'students.override_duplicate',true,  true),
  ('manager',   'records.record_expense',     false, false),
  ('secretary', 'records.record_expense',     true,  false),
  ('manager',   'records.submit_end_of_day',  false, false),
  ('secretary', 'records.submit_end_of_day',  true,  false),
  ('manager',   'records.approve_close_day',  true,  false),
  ('secretary', 'records.approve_close_day',  false, false),
  ('manager',   'payments.edit',              true,  false),
  ('secretary', 'payments.edit',              true,  true);

-- ============================================================
-- 6. RECEIPT FORMAT → R-0041 style (matches the design)
-- ============================================================
create or replace function public.create_receipt_for_payment()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.receipts (payment_id, receipt_no)
  values (new.id, 'R-' || lpad(nextval('receipt_number_seq')::text, 4, '0'));
  return new;
end;
$$;

-- ============================================================
-- 7. ROW-LEVEL SECURITY FOR THE NEW TABLES
-- ============================================================
alter table public.schedule_slots   enable row level security;
alter table public.slot_assignments enable row level security;
alter table public.attendance       enable row level security;
alter table public.daily_closures   enable row level security;
alter table public.notifications    enable row level security;
alter table public.app_settings     enable row level security;
alter table public.role_permissions enable row level security;

-- Manager: full access
create policy mgr_slots  on public.schedule_slots   for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_sassign on public.slot_assignments for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_att    on public.attendance       for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_close  on public.daily_closures   for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_set    on public.app_settings     for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');
create policy mgr_perm   on public.role_permissions for all using (public.get_my_role()='manager') with check (public.get_my_role()='manager');

-- Secretary: manage scheduling + attendance; submit (not close) days
create policy sec_slots_read on public.schedule_slots
  for select using (public.get_my_role()='secretary');
create policy sec_sassign on public.slot_assignments
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');
create policy sec_att on public.attendance
  for all using (public.get_my_role()='secretary') with check (public.get_my_role()='secretary');
create policy sec_close_read on public.daily_closures
  for select using (public.get_my_role()='secretary');
create policy sec_set_read on public.app_settings
  for select using (public.get_my_role()='secretary');
create policy sec_perm_read on public.role_permissions
  for select using (public.get_my_role()='secretary');

-- Notifications: you see what's addressed to you or your role
create policy notif_read on public.notifications
  for select using (
    recipient_user = auth.uid()
    or recipient_role = public.get_my_role()
  );
create policy notif_mark_read on public.notifications
  for update using (
    recipient_user = auth.uid()
    or recipient_role = public.get_my_role()
  );

-- ============================================================
-- DrivePro / Quick Start Pro — 06_client_feedback_updates.sql  (run SIXTH)
-- Changes driven by the 2026-07 meeting with the school owner:
--   granular licence pipeline, enrolment type (D/L/DL),
--   vehicle-linked expenses, driver attribution on attendance,
--   one-query student profile, and closing a real permissions gap
--   (secretary could delete payments to route around the
--   students-delete restriction and reissue receipts)
-- ============================================================

-- ============================================================
-- 1. ENROLMENT TYPE (Driving only / Licence only / Driving + Licence)
--    Gates whether the licence pipeline applies to a student at all.
-- ============================================================
create type enrolment_type as enum ('driving_only', 'licence_only', 'driving_and_licence');

alter table public.students
  add column enrolment_type enrolment_type not null default 'driving_and_licence';

-- ============================================================
-- 2. LICENCE TRACKING — replace the single "stage" enum with
--    explicit, independently-dated fields. The client needs to see
--    eye test, learner licence, a future-dated exam date, and the
--    exam result all at once — a single "current stage" column
--    can't hold that (advancing it would overwrite earlier data).
-- ============================================================
create type licence_exam_result as enum ('pending', 'passed', 'failed');

alter table public.licence_tracking
  add column eye_test_done          boolean not null default false,
  add column eye_test_date          date,
  add column learner_licence_issued boolean not null default false,
  add column learner_licence_date   date,
  add column exam_date              date,
  add column exam_result            licence_exam_result not null default 'pending',
  add column licence_issued         boolean not null default false,
  add column licence_issued_date    date;

-- Best-effort migration of existing rows from the old stage enum
update public.licence_tracking
set eye_test_done          = stage in ('learner_permit','theory_test','practical_test','licence_issued'),
    learner_licence_issued = stage in ('learner_permit','theory_test','practical_test','licence_issued'),
    exam_result             = case when stage = 'licence_issued' then 'passed'::licence_exam_result
                                    else 'pending'::licence_exam_result end,
    licence_issued          = stage = 'licence_issued',
    licence_issued_date     = case when stage = 'licence_issued' then updated_at::date end;

-- CASCADE: v_dashboard_stats (defined earlier in this file) still
-- references this column. It's redefined without the dependency later
-- in this same file (see "8. DASHBOARD STATS" below), so the
-- CASCADE-dropped view is safely recreated before this transaction ends.
alter table public.licence_tracking drop column stage cascade;
drop type licence_stage;

-- One licence record per student
alter table public.licence_tracking
  add constraint uq_licence_student unique (student_id);

create trigger trg_touch_licence before update on public.licence_tracking
  for each row execute function public.touch_updated_at();

-- ============================================================
-- 3. EXPENSES — trace fuel/maintenance costs to one of the vehicles
-- ============================================================
alter table public.expenses
  add column vehicle_id uuid references public.vehicles (id) on delete set null;

create index idx_expenses_vehicle on public.expenses (vehicle_id);

-- ============================================================
-- 4. ATTENDANCE — driver/instructor attribution, for the
--    "lessons per driver" report (e.g. Total 100, Oku 40, Isaac 20)
-- ============================================================
alter table public.attendance
  add column driver_id uuid references public.staff (id);

create index idx_attendance_driver on public.attendance (driver_id);

create or replace view public.v_lessons_per_driver as
select
  sf.id                            as driver_id,
  sf.first_name || ' ' || sf.last_name as driver_name,
  count(*)                         as lessons_taken
from public.attendance a
join public.staff sf on sf.id = a.driver_id
where a.status in ('present', 'late')
group by sf.id, sf.first_name, sf.last_name
order by lessons_taken desc;

-- ============================================================
-- 5. COURSE DURATION — the school deliberately does not promise a
--    fixed timeline ("6 weeks"); lesson count is the real commitment.
--    Make duration optional instead of ripping out the column.
-- ============================================================
alter table public.driving_packages
  alter column duration_weeks drop not null;

alter table public.driving_packages
  drop constraint driving_packages_duration_weeks_check;
alter table public.driving_packages
  add constraint driving_packages_duration_weeks_check
    check (duration_weeks is null or duration_weeks > 0);

-- ============================================================
-- 6. STUDENT PROFILE — one query for the "at a glance" screen:
--    payments, registration date, lessons taken, licence status
-- ============================================================
create or replace view public.v_student_profile as
select
  s.id,
  s.student_number,
  s.first_name || ' ' || s.last_name as student_name,
  s.status,
  s.enrolment_type,
  s.registration_date,
  s.phone,
  s.email,
  s.address,
  s.emergency_contact,
  s.photo_url,
  coalesce(bal.total_fees, 0)       as total_fees,
  coalesce(bal.total_paid, 0)       as total_paid,
  coalesce(bal.balance, 0)          as balance,
  coalesce(lr.total_lessons, 0)     as total_lessons,
  coalesce(lr.lessons_used, 0)      as lessons_used,
  coalesce(lr.lessons_left, 0)      as lessons_left,
  lt.eye_test_done,
  lt.eye_test_date,
  lt.learner_licence_issued,
  lt.learner_licence_date,
  lt.exam_date,
  lt.exam_result,
  lt.licence_issued,
  lt.licence_issued_date,
  -- appended for the edit form (see migration 20260817000018):
  s.first_name,
  s.last_name,
  s.dob,
  s.gender,
  s.ghana_card_no,
  s.id_card_type
from public.students s
left join public.v_student_balances bal on bal.id = s.id
left join public.v_lessons_remaining lr on lr.student_id = s.id
left join public.licence_tracking lt on lt.student_id = s.id;

-- ============================================================
-- 7. LICENCE PIPELINE REPORT — "compile me those whose learner
--    licence has not been done", with summary counts
-- ============================================================
create or replace view public.v_licence_pipeline as
select
  s.id,
  s.student_number,
  s.first_name || ' ' || s.last_name as student_name,
  s.enrolment_type,
  lt.eye_test_done,
  lt.eye_test_date,
  lt.learner_licence_issued,
  lt.learner_licence_date,
  lt.exam_date,
  lt.exam_result,
  lt.licence_issued,
  lt.licence_issued_date
from public.students s
left join public.licence_tracking lt on lt.student_id = s.id
where s.enrolment_type in ('licence_only', 'driving_and_licence');

create or replace view public.v_licence_summary as
select
  count(*)                                                            as total_registered,
  count(*) filter (where not coalesce(learner_licence_issued, false)) as learner_pending,
  count(*) filter (where coalesce(learner_licence_issued, false)
                     and not coalesce(licence_issued, false))         as awaiting_licence,
  count(*) filter (where coalesce(licence_issued, false))             as licence_issued
from public.v_licence_pipeline;

-- ============================================================
-- 8. DASHBOARD STATS — stop counting from lesson_progress (never
--    populated; attendance is the real "lessons done" record) and
--    from the now-removed licence_stage enum
-- ============================================================
create or replace view public.v_dashboard_stats as
select
  (select count(*) from public.students)                                     as total_students,
  (select count(*) from public.students where status = 'active')             as active_students,
  (select coalesce(sum(amount),0) from public.payments
     where date_trunc('month', payment_date) = date_trunc('month', now()))  as revenue_this_month,
  (select coalesce(sum(balance),0) from public.v_student_balances
     where balance > 0)                                                     as outstanding_balances,
  (select count(*) from public.attendance
     where status in ('present','late')
       and date_trunc('month', attendance_date) = date_trunc('month', now())) as lessons_completed,
  (select count(*) from public.licence_tracking where licence_issued)       as licences_issued,
  (select count(*) from public.lesson_schedule
     where lesson_date >= current_date and status='scheduled')              as upcoming_lessons,
  (select coalesce(sum(amount),0) from public.expenses
     where date_trunc('month', expense_date) = date_trunc('month', now())) as expenses_this_month;

-- ============================================================
-- 9. CLOSE A PERMISSIONS GAP (real incident, not hypothetical)
--    Client described a secretary deleting and recreating student
--    profiles to force fresh receipt numbers after direct editing
--    was blocked. `payments.student_id` already uses ON DELETE
--    RESTRICT, which should prevent that — but the secretary policy
--    below was `for all`, meaning she could delete the payments
--    first to clear the way, then delete the student. Nothing in
--    role_permissions ever granted secretaries payments.delete or
--    students.delete (students.delete is explicitly false there);
--    RLS just wasn't enforcing it. Tightening it here to match what
--    was already decided.
-- ============================================================
drop policy if exists sec_pay on public.payments;
create policy sec_pay_read on public.payments
  for select using (public.get_my_role() = 'secretary');
create policy sec_pay_insert on public.payments
  for insert with check (public.get_my_role() = 'secretary');
create policy sec_pay_update on public.payments
  for update using (public.get_my_role() = 'secretary')
  with check (public.get_my_role() = 'secretary');
-- No delete policy for secretary: only the manager (mgr_pay, for all) can delete a payment.

drop policy if exists sec_students on public.students;
create policy sec_students_read on public.students
  for select using (public.get_my_role() = 'secretary');
create policy sec_students_insert on public.students
  for insert with check (public.get_my_role() = 'secretary');
create policy sec_students_update on public.students
  for update using (public.get_my_role() = 'secretary')
  with check (public.get_my_role() = 'secretary');
-- No delete policy for secretary: only the manager (mgr_students, for all) can delete a student.

-- ============================================================
-- 07_custom_auth.sql  (run SEVENTH)
-- public.users was originally 1:1 with Supabase Auth (auth.users),
-- from before the team settled on a custom Express + JWT + bcrypt
-- backend (ADR-002, ADR-004) that never calls Supabase Auth. That FK
-- blocks inserting a user row without first creating a matching
-- auth.users row, and there was nowhere to store a bcrypt hash.
-- ============================================================

alter table public.users drop constraint if exists users_id_fkey;
alter table public.users alter column id set default gen_random_uuid();

alter table public.users add column if not exists password_hash text;

-- Existing rows (manager@drivepro.test, secretary@drivepro.test) were
-- provisioned through Supabase Auth directly and have no password_hash
-- yet — the Express login endpoint treats a null hash as "account not
-- yet provisioned" and rejects the login rather than crashing on
-- bcrypt.compare(password, null). Not enforced NOT NULL here so this
-- migration stays safe to run before those rows are backfilled.

-- ============================================================
-- 08_revoked_tokens.sql  (run EIGHTH)
-- JWTs are stateless and can't be invalidated on their own. Logout
-- (#7) needs a denylist: every issued token carries a `jti` claim,
-- and logging out records that jti here until the token would have
-- expired anyway. The auth middleware checks this table on every
-- request.
-- ============================================================

create table if not exists public.revoked_tokens (
  jti        uuid primary key,
  expires_at timestamptz not null,
  revoked_at timestamptz not null default now()
);

create index if not exists idx_revoked_tokens_expires_at on public.revoked_tokens (expires_at);

-- ============================================================
-- 09_audit_attribution.sql
-- The Express backend connects via a plain pg pool with its own
-- JWT/bcrypt auth (ADR-003/ADR-004), bypassing Supabase Auth
-- entirely. auth.uid() reads a GUC that only PostgREST/Supabase's
-- client sets, so it always resolves to NULL through our connection
-- and audit_logs.user_id would silently stay NULL for every write
-- we make. Attribute writes via an app-level GUC instead, set
-- transaction-locally by Express (see backend/src/db.ts
-- withUserContext) around each authenticated write.
-- ============================================================

create or replace function public.audit_changes()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.audit_logs (user_id, table_name, record_id, action, old_data, new_data)
  values (
    nullif(current_setting('app.current_user_id', true), '')::uuid,
    tg_table_name,
    coalesce((to_jsonb(new) ->> 'id'), (to_jsonb(old) ->> 'id')),
    tg_op,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;
